<?php
 ini_set('display_errors', 1);
 ini_set('display_startup_errors', 1);
 error_reporting(E_ALL);


$order = $block->getOrder($block->getOrderId()); 
$orderid=$block->getOrderId();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
$order = $objectManager->get('Magento\Sales\Model\Order')->load($orderid);
$ordercollection=$order->getItemsCollection()->getData();
?>



<?php 
echo 'START TEST GET ORDER ID <br />';

echo  "Order ID:".$orderid."<br/>";
echo 'END TEST GET ORDER ID <br />';


?>
